---
title: "Linear Models"
author: "Anand Rajan"
date: "11/16/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```


Visualizations

```{r}
nyc_airbnb %>% 
  ggplot(aes(x=stars, y=price)) + geom_point()
```

Let's fit a linear model...

```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)

fit
```

```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(term = str_replace(term, "borough", "Boroough: ")) %>% 
  select(term, estimate, p.value)
```

```{r}
 modelr::add_residuals(nyc_airbnb,fit) %>% 
  ggplot(aes(x=resid)) + geom_density() + xlim(-200,200)
```

```{r}
 nyc_airbnb %>% 
  relocate(borough) %>% 
  nest(data = price:room_type) %>% 
  mutate(
    lm_fits = map(.x = data, ~lm(price ~ stars + room_type, data = .x)), 
    lm_results = map(lm_fits, broom::tidy)
  ) %>% 
  select (borough, lm_results) %>% 
  unnest(lm_results) %>% 
  filter(term == "stars")
```


```{r}
lm_results_df =
nyc_airbnb %>% 
  filter(borough == "Manhattan") %>% 
  select(-borough) %>% 
  relocate (neighborhood) %>% 
  nest(data = price:room_type) %>% 
  mutate(
    lm_fits = map(.x=data, ~lm(price ~ stars + room_type, data = .x)), 
    lm_results = map(lm_fits, broom::tidy)
  ) %>%  
  select(neighborhood,lm_results) %>% 
  unnest(lm_results)
```


```{r}
manhattan_airbnb =
  nyc_airbnb %>% 
  filter(borough == "Manhattan")

manhattan_nest_lm_res =
  manhattan_airbnb %>% 
  nest(data = -neighborhood) %>% 
  mutate(
    models = map(data, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(-data, -models) %>% 
  unnest(results)

manhattan_nest_lm_res %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

## Logistic Regression
 
```{r}
nyc_airbnb %>% 
  mutate (
    exepensive_apt = as.numeric(price > 500)
  )
```

Let's fit a logistic regression for binary outcome

```{r}
logistic_fit =
  glm(
  exepensive_apt ~ stars + borough, 
  data = nyc_airbnb,
  family = binomial())
```

