---
title: "Writing functions"
author: "Anand Rajan"
date: "11/18/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(echo = TRUE)

set.seed(1)
```

## Simple

```{r}
x_vector = rnorm(30, mean = 5, sd = 3)


(x_vector - mean(x_vector)) / sd(x_vector) 
```

I want a function to compute z-scores

```{r}
z_score = function(x) {
  
  if(!is.numeric(x)) {
   stop("Input must be numeric") 
  }
  
  if(length(x) < 3) {
    stop("Input must have at least three numbers")
  }
 z = (x - mean(x)) / sd(x)
z
  
  
}


```

Try my function on some other things.

```{r error=TRUE}
z_scores(3)
z_scores("my name is jeff")

z_scores(mtcars)
z_scores(c(TRUE,TRUE,FALSE,TRUE))
```

## Multiple Outputs

```{r}
mean_and_sd = function(x) {
  
  if(!is.numeric(x)) {
   stop("Input must be numeric") 
  }
  
  if(length(x) < 3) {
    stop("Input must have at least three numbers")
  }
 
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```

checking functions

```{r}

mean_and_sd(x_vector)
```

## Multiple Inputs

Do this with a function
```{r}
sim_data = 
  tibble(
    x = rnorm(100, mean = 4 , sd=3)
  )

sim_data %>% 
  summarize(
    mean = mean(x),
    sd=sd(x)
  )
```



```{r}

sim_mean_sd= function(samp_size, mu, sigma){


  sim_data = 
    tibble(
       x = rnorm(n=samp_size, mean = mu, sd=sigma)
     )

  sim_data %>% 
      summarize(
        mean = mean(x),
        sd=sd(x)
  )
}

sim_mean_sd(100,6,3)
```


Positional vs named matching
-named matching is preferred
